version: '3.9'

services:

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    volumes:
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: Guga1957!
      POSTGRES_DB: user_db
      POSTGRES_USER: postgres
