server:
  port: 8081
  servlet:
    context-path: /user

spring:
  application:
    name: ms-user
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/user_db
    username: postgres
    password: Guga1957!
  jpa:
    hibernate:
      ddl-auto: update

